#ifndef LOWPASS_H_
#define LOWPASS_H_
/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 11-Jan-2019 21:06:41
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
//const int BL = 29;
//const real32_T B[29] = {
//   0.001788277179,-0.002203474287, 0.002879403066,-0.003349118168, 0.002751868684,
//  -1.177569357e-17,-0.005945665762,  0.01575740241, -0.02946314029,  0.04629049823,
//   -0.06468687207,   0.0825278908, -0.09747879207,   0.1074323803,   0.8873986602,
//     0.1074323803, -0.09747879207,   0.0825278908, -0.06468687207,  0.04629049823,
//   -0.02946314029,  0.01575740241,-0.005945665762,-1.177569357e-17, 0.002751868684,
//  -0.003349118168, 0.002879403066,-0.002203474287, 0.001788277179
//};
#endif
